### ISSUE TITLE
Auto generate shader input tags.

### ISSUE THREAD

**Issue by Makogan** [Makogan/NeverEngine#1]
We need a templated function that takes in an arbitrary type as a template parameter and generates a bitmask representing the input parameters (vertices, uvs, normals...) present in that type.

The templated function should be added in `Src/Engine/Shared/Shared.hpp` and use the attribute enumerators defined in the same file.

To test the feature, copy the BaseExample directory and rename all isntances of `BaseExample` in that directory to `Temporary`. Then do your experiments in that new demo.

Useful resources:

* https://en.cppreference.com/w/cpp/language/constraints
* Src/Engine/Animation/AnimationMesh.hpp

**Comment by jamaliki** [comment]
This was addressed here: https://github.com/Makogan/NeverEngine/pull/2
